dream3d_pipeline_runner_location:
  version6.5: '../DREAM3D-6.5.49-Win64/PipelineRunner.exe'
  version6.13: '../DREAM3D-6.1.3-Win64/PipelineRunner.exe'

dream3d_pipeline_template_location:
  ctf:
    version6.13: '../Templates/PW_CTF_routine_v613.json'
    version6.5: '../Templates/PW_CTF_routine_v65.json'
  ang:
    version6.13: '../Templates/PW_ANG_routine_v613.json'
    version6.5: '../Templates/PW_ANG_routine_v65.json'

error_handling:
  timeout_seconds: 120 #code will try to run Dream.3D pipelines and check for presence of expected output files. this sets the max time allowable for the GUI job monitor --it should not affect or terminate jobs running in the background that may take longer